#!/bin/bash
if [ $(whoami) != "root" ];then
    echo "You must be root to run script."
    exit 1
fi
cd ..
pip install -r blackbox/requirements.txt
cp -R blackbox/ /opt/
echo '#!/bin/sh' > /bin/blackbox
echo 'python /opt/blackbox/blackbox.py "$@"' >> /bin/blackbox
chmod 755 /bin/blackbox
chmod +x /bin/blackbox
rm -rf blackbox/
blackbox
if [ $? -eq 0 ]; then
	echo "WORKED ! NOW YOU CAN USE command! : blackbox"
else
    echo "ERROR FAIL!"
    exit 1
fi
